UPDATE regs SET PROVEEDOR = 'CIE CONSTRUCTORA EMPRESARIAL S.R.L' WHERE PROVEEDOR IN ('CIE CONSULTORA EMPRESARIAL EIRL', 'CIE CONSULTORA SRL');
UPDATE regs SET PROVEEDOR = 'VASQUEZ CCENCHO IRAIDA' WHERE PROVEEDOR IN ('VASQUEZ CCHENCHO ARAIDA');
UPDATE regs SET PROVEEDOR = 'COLCA TOVAR RAUL IGNACIO' WHERE PROVEEDOR IN ('COLCA TOVAR RAUL - LOCAL COMUNAL');
UPDATE regs SET PROVEEDOR = 'CONAFOVICER' WHERE PROVEEDOR IN ('CONAFOVICER JUNIO');
UPDATE regs SET PROVEEDOR = 'CORPORACION M&R MAQ S.A.C' WHERE PROVEEDOR IN ('CORPORACION M&R SAC');
UPDATE regs SET PROVEEDOR = 'LADRON DE GUERVARA BASALDUA ESTELA NILDA' WHERE PROVEEDOR IN ('LADRON DE GUEVARA BASALDUA ESTELA NILDA-AGROHERRAMIENTAS GANAGRO');
UPDATE regs SET PROVEEDOR = 'MARTINEZ CAMARENA IBSEN GERDY' WHERE PROVEEDOR IN ('MARTINEZ CAMARENA IBSEN Y MALDONADO CHAVEZ ROBERTO');
UPDATE regs SET PROVEEDOR = 'MATIAS CERVANTES LUIS ALBERTO' WHERE PROVEEDOR IN ('MATIAS CERVANTES LUIS ALBERTO-SEÑALIZACION - SEÑAFORIZACION & MAS');
