
UPDATE regs SET PROVEEDOR = 'ABEL GONZALES SULLCARAY' WHERE id>0 AND PROVEEDOR IN ('GONZALES SULLCARAY ABEL');
UPDATE regs SET PROVEEDOR = 'ACEVEDO MAYTA JENNER' WHERE id>0 AND PROVEEDOR IN ('JENNER ACEVEDO MAYTA');
UPDATE regs SET PROVEEDOR = 'ADAIR AROLDI CHALCO BONIFACIO' WHERE id>0 AND PROVEEDOR IN ('CHALCO BONIFACIO ADAIR AROLDI', 'CHALCO BONIFACIO ADAIR');
UPDATE regs SET PROVEEDOR = 'ADOLFO HITLER OLIVAR ROJAS' WHERE id>0 AND PROVEEDOR IN ('OLIVAR ROJAS ADOLFO HITLER');
UPDATE regs SET PROVEEDOR = 'AQUASISTEMAS G&J S.A.C' WHERE id>0 AND PROVEEDOR IN ('AGUASISTEMAS G&J S.A.C');
UPDATE regs SET PROVEEDOR = 'ALBERT TORIBIDO VELASCO' WHERE id>0 AND PROVEEDOR IN ('ALRBERT TORIBIO VELASCO');
UPDATE regs SET PROVEEDOR = 'ALCARRAZ HUILCA DAVID ENRIQUE' WHERE id>0 AND PROVEEDOR IN ('ALCARRAZ HUILCA DAVID ENRIQUE', 'DAVID ENRIQUE HUILCA ALCARRAZ','ALCARRAS HUALCA DAVID ENRIQUE','ALCARRAZ HUILCA DAVID');
UPDATE regs SET PROVEEDOR = 'ALDANA CONTRERAS ARNULDO' WHERE id>0 AND PROVEEDOR IN ('ARNULDO ALDANA CONTRERAS');
UPDATE regs SET PROVEEDOR = 'ALEJANDRA MARTINEZ AROTOMA' WHERE id>0 AND PROVEEDOR IN ('MARTINEZ AROTOMA ALEJANDRA');
UPDATE regs SET PROVEEDOR = 'ALEJANDRO MONTES LEDEZMA' WHERE id>0 AND PROVEEDOR IN ('MONTES LEDESMA ALEJANDRO');
UPDATE regs SET PROVEEDOR = 'ALIAGA LLANTOY GISELA NINOSKA' WHERE id>0 AND PROVEEDOR IN ('GISELA ALIAGA LLANTOY');
UPDATE regs SET PROVEEDOR = 'ALVAREZ BARRIENTOS OSWALDO' WHERE id>0 AND PROVEEDOR IN ('OSWALDO ALVAREZ BARRIENTOS');
UPDATE regs SET PROVEEDOR = 'ALVARO JESUS GOMEZ HERMOZA' WHERE id>0 AND PROVEEDOR IN ('GOMEZ HERMOZA ALVARO JESUS','ALVARO GOMEZ HERMOZA');
UPDATE regs SET PROVEEDOR = 'AMANCIA ALBERTA RAMIREZ DE ALEJANDRO' WHERE id>0 AND PROVEEDOR IN ('RAMIREZ DE ALE MANCIA ALBERTA');
UPDATE regs SET PROVEEDOR = 'AMBROSIO ARTEZANO EDSON GORGE' WHERE id>0 AND PROVEEDOR IN ('EDSON GEORGE AMBROSIO ARTEZANO');
UPDATE regs SET PROVEEDOR = 'BENDEZU ACEVEDO ANDER LUIS' WHERE id>0 AND PROVEEDOR IN ('BENDEZU ACEVEDO ANDER', 'ANDER BENDEZU ACEVEDOR', 'BENDEZU ACEVEDO ANDER LUIS','ANDER BENDEZU ACEVEDO');
UPDATE regs SET PROVEEDOR = 'CHAVEZ ATUNGA ANGELY' WHERE id>0 AND PROVEEDOR IN ('CHAVEZ ATUNGA ANGELY','ANGELY CHAVEZ ATUNGA', 'ANGHE LY CHAVEZ ATUNGA', 'CHAVEZ ATUNGA ANGHE LY', 'ANGHE LY CHAVEZ ATUNCA');
UPDATE regs SET PROVEEDOR = 'ANMA IMPORTACIONES E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('ANMA IMPORTACIONES E.I.R.L','ANMA IMPORTACIONES');
UPDATE regs SET PROVEEDOR = 'APARCO LIMA VICTOR' WHERE id>0 AND PROVEEDOR IN ('VICTOR APARCO LIMA');
UPDATE regs SET PROVEEDOR = 'ARANDA CANCHUMONI KEVIN' WHERE id>0 AND PROVEEDOR IN ('KEVIN ARANDA CANCHUMONI', 'ARANDA CANHUMONI KEVIN', 'ARANDA CANCHUMONI KEVIN RAUL');
UPDATE regs SET PROVEEDOR = 'ARAUJO BERAUN EVER' WHERE id>0 AND PROVEEDOR IN ('EVER ARAUJO BERAUN');
UPDATE regs SET PROVEEDOR = 'ARISTE CALDERON ADELA' WHERE id>0 AND PROVEEDOR IN ('ARISTE CALDERON ADELE');
UPDATE regs SET PROVEEDOR = 'PALACIOS SANTOS MILAGROS' WHERE id>0 AND PROVEEDOR IN ('MILAGROS PALACIOS SANTOS', 'PALACIOS SANTOS MILAGROS');
UPDATE regs SET PROVEEDOR = 'AROTOMA HUAMANI PABLO' WHERE id>0 AND PROVEEDOR IN ('PABLO ARTOMA HUAMANI');
UPDATE regs SET PROVEEDOR = 'ASTUDILLO CORNEJO JORGE LUIS' WHERE id>0 AND PROVEEDOR IN ('ASTUDILLO CORNELIO JORGE LUIS');
UPDATE regs SET PROVEEDOR = 'AUTOMOVILES S.A' WHERE id>0 AND PROVEEDOR IN ('MUTOMOVILES S.A');
UPDATE regs SET PROVEEDOR = 'AYALA ALVAREZ LUZ' WHERE id>0 AND PROVEEDOR IN ('LUZ AYALA ALVAREZ', 'LUZ LUZMILA AYALA ALVAREZ');
UPDATE regs SET PROVEEDOR = 'AYALA GOMEZ ANDERSON' WHERE id>0 AND PROVEEDOR IN ('AYALA GOMEZ JIMMY ANDERSON');
UPDATE regs SET PROVEEDOR = 'AYDE VERONICA COTRINA MIRANDA' WHERE id>0 AND PROVEEDOR IN ('COTRINA MIRANDA AYDE VERONICA');
UPDATE regs SET PROVEEDOR = 'BALDEON LANDEO DANNY WILFREDO' WHERE id>0 AND PROVEEDOR IN ('DANNY BALDEON LANDEO', 'BALDEON LANDEO DANNY WILFREDO', 'DANNY WILFERSO BALDEON LANDEO','BALDEON LANDEO DANNY');
UPDATE regs SET PROVEEDOR = 'BANCES AQUINO CLEMENCIA ISABEL' WHERE id>0 AND PROVEEDOR IN ('CLEMENCIA BANCES AQUINO');
UPDATE regs SET PROVEEDOR = 'BBVA CONTINENTAL' WHERE id>0 AND PROVEEDOR IN ('BBVA CONTINENTAL','BANCO CONTINENTAL');
UPDATE regs SET PROVEEDOR = 'BERTHA ESPINAL DE GAMARRA' WHERE id>0 AND PROVEEDOR IN ('ESPINAL DE GAMARRA BERTHA');
UPDATE regs SET PROVEEDOR = 'BORJA CCANTO DENIS JHONATHAN' WHERE id>0 AND PROVEEDOR IN ('BORJA CCANTO DENIS JONATHAN');
UPDATE regs SET PROVEEDOR = 'BORJA ROMAN JAIME' WHERE id>0 AND PROVEEDOR IN ('BROJA ROMAN JAIME');
UPDATE regs SET PROVEEDOR = 'GRUPO CARBAJAL & REPRESENTACIONES S.A.C' WHERE id>0 AND PROVEEDOR IN ('GRUPO CARBAJAL & REPRESENTACIONES S.A.C','BRUPO CARBAJAL & REPRESENTACIONES S.A.C' , 'GRUPO CARBAL & REPRESENTACIONES S.A.C');
UPDATE regs SET PROVEEDOR = 'BUILDERS TROOP MAQUINARIAS & INGENIEROS S.A.C' WHERE id>0 AND PROVEEDOR IN ('BUILDERS TROOP MAQUINARIAS & INGENIEROS S.A.C', 'BUILDERS TROOP MAQUINARIAS & INGENIERIA S.A.C','BULDERS TROOP MAQUINARIA S.A.C');
UPDATE regs SET PROVEEDOR = 'C3 INGENIERIA ESPECIALIZADA S.A.C' WHERE id>0 AND PROVEEDOR IN ('C3 INGENIERIA ESPECIALZIADA SAC');
UPDATE regs SET PROVEEDOR = 'CACCHI QUIROZ RAYSA SADITH' WHERE id>0 AND PROVEEDOR IN ('CHACCHI QUIROZ RAYSA SADITH');
UPDATE regs SET PROVEEDOR = 'CARDENAS MIRANDA ELIO' WHERE id>0 AND PROVEEDOR IN ('ELIO CARDENAS MIRANDA','CADENAS MIRANDA ELIO');
UPDATE regs SET PROVEEDOR = 'CAHUANA HIDALGO MAURINO' WHERE id>0 AND PROVEEDOR IN ('CAHUANA HIDALGO MAURINO SILVESTRE');
UPDATE regs SET PROVEEDOR = 'CALDAS ROMERO DULCE FELITA' WHERE id>0 AND PROVEEDOR IN ('DULCE CALDAS ROMERO');
UPDATE regs SET PROVEEDOR = 'CAMARGO MAYTA CANDY' WHERE id>0 AND PROVEEDOR IN ('CANDY CAMARGO MAYTA', 'CAMARGO MAYTA CANDY VERONICA');
UPDATE regs SET PROVEEDOR = 'CAMIPPEL S.A.C' WHERE id>0 AND PROVEEDOR IN ('CAPIMEL S.A.C');
UPDATE regs SET PROVEEDOR = 'CAMPOS CABELLO MARIVEL' WHERE id>0 AND PROVEEDOR IN ('MARIVEL CAMPOS CABELLO');
UPDATE regs SET PROVEEDOR = 'CAMPOS LOPEZ YSAMAHAR JHORGE' WHERE id>0 AND PROVEEDOR IN ('CAMPOS LOPEZ YSAMAR JHORGE');
UPDATE regs SET PROVEEDOR = 'CANCHANCYA BALVIN DANIEL ABRHAM' WHERE id>0 AND PROVEEDOR IN ('CANCHANYA BALVIN DANIEL ABRAHAM JACOB ( AMAUTA)');
UPDATE regs SET PROVEEDOR = 'CANCHANYA ROJAS EULOGIO BALERIO' WHERE id>0 AND PROVEEDOR IN ('EULOGIO BALERIO CANCHANYA ROJAS', 'EULOGIO BAERIO CANCHANYA ROJAS', 'EULOGIO BALERIO CANCHANCYA ROJAS', 'EULOGIO BALERO CANCHANYA ROJAS', 'EULOGIO BALERIO CANCHANYA');
UPDATE regs SET PROVEEDOR = 'CANTO AVILA JACKELINE' WHERE id>0 AND PROVEEDOR IN ('JACKELINE CANTO AVILA', 'CANTO AVILA JACKELINE MARINA', 'JACKELINE MARINA CANTO AVILA');
UPDATE regs SET PROVEEDOR = 'CAPCHA LEIVA EDGAR' WHERE id>0 AND PROVEEDOR IN ('EDGAR CAPCHA LEYVA');
UPDATE regs SET PROVEEDOR = 'CARBAJAL CHAHUAYLA YURI JHON' WHERE id>0 AND PROVEEDOR IN ('CARBAJAL CHAHUAYLA YURI');
UPDATE regs SET PROVEEDOR = 'CARRASCO HUAMAN ELFA' WHERE id>0 AND PROVEEDOR IN ('CARRASCO HUAMAN ELFA', 'HUAMAN CARRASCO ELFA', 'CARERASCO HUAMAN ELFA');
UPDATE regs SET PROVEEDOR = 'CARHUANCHO ÑAÑA ROCIO' WHERE id>0 AND PROVEEDOR IN ('ROCIO CARHUANCHO ÑAÑA', 'ROCIO CAHUANCHO ÑAÑA', 'ROCIO CARHUANCAHO ÑAÑA', 'ROCIO CARHUANCHO');
UPDATE regs SET PROVEEDOR = 'CARLOS FERRUZO CAMPOS' WHERE id>0 AND PROVEEDOR IN ('FERRUZO CAMPOS CARLOS RAUL');
UPDATE regs SET PROVEEDOR = 'CARMAGO MAYTA CANDY' WHERE id>0 AND PROVEEDOR IN ('CARMARGO MAYTA CANDY');
UPDATE regs SET PROVEEDOR = 'CARMEN MILENA CHAMORRO ACOSTA' WHERE id>0 AND PROVEEDOR IN ('MILENA CARMEN CHAMORRO ACOSTA');
UPDATE regs SET PROVEEDOR = 'CASAS YUPANQUI JULIO MARCIAL' WHERE id>0 AND PROVEEDOR IN ('COSAS YUPANQUI JULIO MARCIAL');
UPDATE regs SET PROVEEDOR = 'CASTRO PEREZ MEYER' WHERE id>0 AND PROVEEDOR IN ('MEYER CASTRO PEREZ', 'MAYER CASTRO PEREZ', 'MEYER FIDEL CASTRO PEREZ');
UPDATE regs SET PROVEEDOR = 'CASTRO SANABRIA JUDITH SANABRIA' WHERE id>0 AND PROVEEDOR IN ('CASTRO SANARIA JUDITH SIANA');
UPDATE regs SET PROVEEDOR = 'CECY MELINA ZARATE GUILLERMO' WHERE id>0 AND PROVEEDOR IN ('ZARATE GUERRERO CECY MELINA');
UPDATE regs SET PROVEEDOR = 'CENRTO CERAMICO TITO E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('CENTRO CERAMICO TITO E.I.R.L');
UPDATE regs SET PROVEEDOR = 'CERRON INGA EDSEN JORGE' WHERE id>0 AND PROVEEDOR IN ('JORGE CERRON INGA');
UPDATE regs SET PROVEEDOR = 'CHALCO MEZA MERY LILIANA' WHERE id>0 AND PROVEEDOR IN ('MERY LILIANA CHALCO MEZA');
UPDATE regs SET PROVEEDOR = 'CHAMORRO MATOS ANDRES' WHERE id>0 AND PROVEEDOR IN ('MATOS CHAMORRO ANDRES HORACIO');
UPDATE regs SET PROVEEDOR = 'CHIQUILLANQUI CHILENO TEOFILA CIRILA' WHERE id>0 AND PROVEEDOR IN ('CHUQUILLANQUI CHILENO TEOFILA CIRILA', 'CHUQUILLANQUI CHILECNO TEOFILA CIRILA');
UPDATE regs SET PROVEEDOR = 'CIA MACAÉ S.A.C' WHERE id>0 AND PROVEEDOR IN ('COMPAÑÍA MACAE S.A.C');
UPDATE regs SET PROVEEDOR = 'CIE CONSTRUCTORA EMPRESARIAL S.R.L' WHERE id>0 AND PROVEEDOR IN ('EMPRESA CONSTRUCTORA JSR S.A.C');
UPDATE regs SET PROVEEDOR = 'COAMISEG' WHERE id>0 AND PROVEEDOR IN ('D & L COAMISEG');
UPDATE regs SET PROVEEDOR = 'COCA PEREZ YANETH LILIANA' WHERE id>0 AND PROVEEDOR IN ('YANETH LILIANA COCA PEREZ');
UPDATE regs SET PROVEEDOR = 'COMUNIDAD CAMPESINA DE CHONGOS' WHERE id>0 AND PROVEEDOR IN ('COMUNIDAD DE CHONGOS ALTO');
UPDATE regs SET PROVEEDOR = 'CONCRETOS Y MARMOLES PERALTA CONSTRUCTORA E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('CONCRETOS Y MARMOLES PRALTA CONSTRUCTORA E.I.R.L');
UPDATE regs SET PROVEEDOR = 'CONTRATISTAS MINEROS ADISOL E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('CONTRATISTAS MINEROS ADISOL E.I.R.L','CONSTRATISTAS MINEROS ADISOL E.I.R.L');
UPDATE regs SET PROVEEDOR = 'CONSTRUCTORA INFRAGROUP S.A.C' WHERE id>0 AND PROVEEDOR IN ('CONSTRCUTORA INFRAGROUP S.A.C','CONSTRUCTORA INFRAGROUP S.A.C', 'CONSTRUCTORA INFRAGRUP S.A.C', 'CONSTRUCTORA INFRAGROUO S.A.C');
UPDATE regs SET PROVEEDOR = 'CONTRERAS NUÑEZ MONICA' WHERE id>0 AND PROVEEDOR IN ('CONSTRERAS NUÑES MONICA','CONTRERAS NUÑEZ MONICA');
UPDATE regs SET PROVEEDOR = 'CONSTRUCTORA Y CONCRETERA JYR S.A.C' WHERE id>0 AND PROVEEDOR IN ('CONSTRUTORA CONCRETERA JYR S.A.C', 'CONSTRUCTORA CONCRETERA JYR S.A.C');
UPDATE regs SET PROVEEDOR = 'CONSTRUCTORA, CONSULTORA Y MULTISERVICIOS D''LUEMYX S.C.R.L' WHERE id>0 AND PROVEEDOR IN ('CONSTRUCTORA CONSULTORA Y MULTISERVICIOS D''LUMYX S.C.R.L','CONSTRUCTORA, CONSULTORA Y MULTISERVICIOS D''LUEMYX S.C.R.L', 'CONSTRUCTORA CONSULTORA Y MULTISERVICIOS DLUEMYX S.C.R.L');

UPDATE regs SET PROVEEDOR = 'EMPRESA CONSTRUCTORA SERVICIOS Y SUMINISTROS LA MARTINA S.A.C' WHERE id>0 AND PROVEEDOR IN ('EMPRESA CONSTRUCTORA SERVICIOS Y SUMINISTROS LA MARTINA S.A.C','CONSTRUCTORA SERVICIOS Y SUMINISTROS LA MARTINA SAC');

UPDATE regs SET PROVEEDOR = 'CONTASIC S.A' WHERE id>0 AND PROVEEDOR IN ('CONTASIS S.A');
UPDATE regs SET PROVEEDOR = 'CORPORACION E&J MAQUINARIAS E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('COORPORACION E&J MAQUINARIAS E.I.R.L','CORPORACION E&J  MAQUINARIAS E.I.R.L', 'CORPORACION E&J MAQUINARIAS E.I.R.L', 'CORPORACION E&J MAQUINARIA E.I.R.L', 'COORPORACION E6J MAQUINARIA E.I.R.L');
UPDATE regs SET PROVEEDOR = 'COPORACIÓN KAZUKY MERCURY E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('CORPORACION KAZUKY MERCURY E.I.R.L');
UPDATE regs SET PROVEEDOR = 'CORPORACION ROCAP S.A.C' WHERE id>0 AND PROVEEDOR IN ('CORPORACIOB ROCAP S.A.C','CORPORACION ROCAP S.A.C');
UPDATE regs SET PROVEEDOR = 'CORPORACION ACEROS AREQUIPA S.A' WHERE id>0 AND PROVEEDOR IN ('CORPORACION ACERO AREQUIPA S.A');
UPDATE regs SET PROVEEDOR = 'CORPORACION SYR PERU S.A.C' WHERE id>0 AND PROVEEDOR IN ('CORPORACION DYR PERU S.A.C');
UPDATE regs SET PROVEEDOR = 'CORPORACION E INVERSIONES FABRI S.A.C' WHERE id>0 AND PROVEEDOR IN ('CORPORACION EN INVERSIONES FABRI S.A.C', 'CORPORACION E INVERSIONES GABRI S.A.C');

UPDATE regs SET PROVEEDOR = 'CORPORACION HUANCAYO S.A.C' WHERE id>0 AND PROVEEDOR IN ('CORPORCION HUANCAYO S.A.C');
UPDATE regs SET PROVEEDOR = 'CORPORACION K&R PLASTIREY S.A.C' WHERE id>0 AND PROVEEDOR IN ('CORPORAION K&R PLASTIREY');

UPDATE regs SET PROVEEDOR = 'CORPORACION M&R MAQ S.A.C' WHERE id>0 AND PROVEEDOR IN ( 'CORPROACION M&R MAQ SAC');

UPDATE regs SET PROVEEDOR = 'CORPORACION PANCAN E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('CORPORACION PANCAN E.I.R.L','CORPORACION PANCAN');

UPDATE regs SET PROVEEDOR = 'CORPORACION SERMIN E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('CORPORACION SEMIN E.I.R.L','CROPROACION SERMIN EIRL');

UPDATE regs SET PROVEEDOR = 'COTRINA ATENCIO JHON' WHERE id>0 AND PROVEEDOR IN ('JHON COTRINA ATENCIO');
UPDATE regs SET PROVEEDOR = 'CRISTIAN RAMOS' WHERE id>0 AND PROVEEDOR IN ('DR CRISTIAN RAMOS');

UPDATE regs SET PROVEEDOR = 'CRUZ MARCAS RITA' WHERE id>0 AND PROVEEDOR IN ('RITA CRUZ MARCAS');
UPDATE regs SET PROVEEDOR = 'CUCHI CONDOR PERCY' WHERE id>0 AND PROVEEDOR IN ('CUCHO CONDOR PERCY');
UPDATE regs SET PROVEEDOR = 'CYNTHIA BEATRIZ TORRES PRADO' WHERE id>0 AND PROVEEDOR IN ('CYNTHIA BEATRIZ TORRES PRADO', 'TORRES PRADO CYNTHIA BEATRIZ', 'CYNTHIA BEATRIS TORRES PRADO','CYANTHIA BEATRIZ PRADO');
UPDATE regs SET PROVEEDOR = 'CYNTHIA BEATRIZ TORRES PRADO' WHERE id>0 AND PROVEEDOR IN ('CYNTHIA BEATRIS TORRES PRADO', 'CYNTHIA BEATRIZ TORRES PRADO', 'TORRES PRADO CYNTHIA BEATRIZ');

UPDATE regs SET PROVEEDOR = 'D Y M AMPUERO CONSTRUCCION S.A.C' WHERE id>0 AND PROVEEDOR IN ('D Y M AMPUERO CONSTRUCCION S.A.C', 'DYM AMPUERO CONSTRUCCIÓN S.A.C','D Y M AMPUERO CONSTRUCCION');
UPDATE regs SET PROVEEDOR = 'DANIEL HANS VALENTIN VICENTE' WHERE id>0 AND PROVEEDOR IN ('VALENTIN VICENTE DANIEL HANS', 'VICENTE VALENTIN DANIEL');
UPDATE regs SET PROVEEDOR = 'DANIEL VALENTIN' WHERE id>0 AND PROVEEDOR IN ('VALENTIN CONDOR DANIEL');
UPDATE regs SET PROVEEDOR = 'DC & L COAMISEG S.A.C' WHERE id>0 AND PROVEEDOR IN ('DC & L COASMIG S.A.C');
UPDATE regs SET PROVEEDOR = 'DOB EXPRESS INGENIERIA & SOFTWARE S.A.C' WHERE id>0 AND PROVEEDOR IN ('DDB EXPRESS INGENIERIA & SOFTWARE S.A.C','DOB EXPRESS INGENIERIA & SOFTWARE S.A.C', 'SSB EXPRESS INGENIERIA & SOFTWARE S.A.C', 'DOC EXPRESS INGENIERIA & SOFWARE');
UPDATE regs SET PROVEEDOR = 'DE LA CRUZ GARCIA GABRIELA' WHERE id>0 AND PROVEEDOR IN ('GABRIELA DE LA CRUZ GARCIA');
UPDATE regs SET PROVEEDOR = 'DE LA CRUZ HUAMAN EDWIN WILVER' WHERE id>0 AND PROVEEDOR IN ('DE LA CUZ HUAMAN EDWIN WILVER');
UPDATE regs SET PROVEEDOR = 'DENISSE ROXANA HUAMAN DANIEL' WHERE id>0 AND PROVEEDOR IN ('DENISSE ROZANA HUAMAN DANIEL');
UPDATE regs SET PROVEEDOR = 'DIAS AYALA EMILIA' WHERE id>0 AND PROVEEDOR IN ('DIAZ AYALA EMILIA');
UPDATE regs SET PROVEEDOR = 'DIEGO LEANDRO GABRIEL' WHERE id>0 AND PROVEEDOR IN ('LEANDRO GABRIEL DIEGO ALEXIS');
UPDATE regs SET PROVEEDOR = 'DIONISIO FLORES MARLENI' WHERE id>0 AND PROVEEDOR IN ('DIONISIO FLORES MARLENI MARGARITA');

UPDATE regs SET PROVEEDOR = 'DISTRIBUIDORA E INVERSIONES MARBELLA S.A.C' WHERE id>0 AND PROVEEDOR IN ('DISTRIBUDIROA E INVERSIONES MARBELLA SAC','DISTRIBUIDORA E INVERSIONES MARBELLA S.A.C','DISTRIBUIDORA E IMPORTACIONES MARBELLA S.A.C');

UPDATE regs SET PROVEEDOR = 'DISTRIBUIDORA ERICK S.R.L'  WHERE id>0 AND PROVEEDOR IN ('DISTRIBUIDORA ERICK S.R.L','DISTRIBUIDORA EIRCK S.R.L');
UPDATE regs SET PROVEEDOR = 'DOMUN GROUP S.A.C' WHERE id>0 AND PROVEEDOR IN ('DOMUS GROUP S.A.C');
UPDATE regs SET PROVEEDOR = 'ECHABAUDIS MATAMOROS JORGE' WHERE id>0 AND PROVEEDOR IN ('JOEL ECHABAUDIS MATAMOROS', 'JOEL ECHABUDIS MATAMOROS', 'ECHABAUDIS MATAMOROS JORGE LUIS', 'ECHEBAUTIS MATAMOROS JORGE LUIS');
UPDATE regs SET PROVEEDOR = 'GRUPO ECOANDINA S.A.C' WHERE id>0 AND PROVEEDOR IN ('ECOANDINA SAC','ECOANDINA','GRUPO ECOANDINA S.A.C','ECOANDINO S.A.C');

UPDATE regs SET PROVEEDOR = 'EDIFIKA CONSTRUCTORA E INMOBILIARIA E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('EDIFIKA CONSTRUCTORA E INMOBILIARIO E.I.R.L');
UPDATE regs SET PROVEEDOR = 'EDWARD QUEBEDO SANTA CRUZ' WHERE id>0 AND PROVEEDOR IN ('SANTA CRUZ CELIS EDWARD QUEBEDO');
UPDATE regs SET PROVEEDOR = 'EGAS ARROYO ABRAHAM' WHERE id>0 AND PROVEEDOR IN ('EGAS ARROYYO ABRAHAM');
UPDATE regs SET PROVEEDOR = 'ELIAS ALBERTO TUPAC YUPANQUI' WHERE id>0 AND PROVEEDOR IN ('TUPAC YUPANQUI ELIAS ALBERTO', 'ELIAS ALBERTO TUPAC YUPANQUI SOTELO', 'TUPAC YUPANQUI SOTELO ELIAS ALBERTO');
UPDATE regs SET PROVEEDOR = 'ELIAS MOISES GAMBOA PARI' WHERE id>0 AND PROVEEDOR IN ('GAMBOA PARI ELIAS MOISES', 'GAMBOA PARI EILIAS MOISES', 'MOISES GAMBOA PARI', 'GAMBOA PARI ELIAS');
UPDATE regs SET PROVEEDOR = 'ELIAS ALBERTO TUPAC YUPANQUI' WHERE id>0 AND PROVEEDOR IN ('ELIAS TUPAC YUPANQUI SOTELO','TUPAC YUPANQUI ELIAS SOTELO', 'TUPAC YUPANQUI SOTELO', 'ELIAS ALBERTO TUPAC YUPANQUI SOTELO', 'TUPAC YUPANQUI SOTELO ELIAS ALBERTO');
UPDATE regs SET PROVEEDOR = 'NOA CURO JOSUE ELISEO' WHERE id>0 AND PROVEEDOR IN ('NOA CURO JOSUE ELISEO','ELISEO NOA CURO');
UPDATE regs SET PROVEEDOR = 'ELIZABETH AMELIA VELASQEUZ ROMERO' WHERE id>0 AND PROVEEDOR IN ('VELASQUEZ ROMERO ELIZABETH AMELIA');
UPDATE regs SET PROVEEDOR = 'ELIZARES BRAÑES JHON MARVIN' WHERE id>0 AND PROVEEDOR IN ('JHON MARVIN ELIZARES BRAÑES');
UPDATE regs SET PROVEEDOR = 'ELMER OSCAR ZUASNABAR HUARIPATA' WHERE id>0 AND PROVEEDOR IN ('ZUASNABAR HUARIPATA ELMER OSCAR', 'ELMER OSCAR ZUASNABAR HURIPATA');
UPDATE regs SET PROVEEDOR = 'ELVIA CASTELLARES HUAYLINOS' WHERE id>0 AND PROVEEDOR IN ('ELVIA IRENE CASTELLARES HUAYLINOS');
UPDATE regs SET PROVEEDOR = 'ELVIS VILLALOBOS GONZALES' WHERE id>0 AND PROVEEDOR IN ('VILLALOBOS GONZALES ELVIS');
UPDATE regs SET PROVEEDOR = 'EMERSON VELASQUEZ VILLANUEVA' WHERE id>0 AND PROVEEDOR IN ('VELASQUEZ VILLANUEVA EMERSON');
UPDATE regs SET PROVEEDOR = 'EMPRESA CONSTRUCTORA Y SERVICIOS MINEROS JRJ S.A.C' WHERE id>0 AND PROVEEDOR IN ('EMPRESA COSNTRUCTORA Y SERVICIOS MINEROS RJR S.A.C', 'EMRPESA COSNTRUCTORA Y SERVICIOS MINEROS');
UPDATE regs SET PROVEEDOR = 'EMPRESA DE SERVICIOS MULTIPLES VITAS E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('EMPRESA DE SERVICIOS MULTIPLES VITAS E.I.R.L','EMPRESA DE SERVICIOS MULTIPLES VITAS');


UPDATE regs SET PROVEEDOR = 'ENTEL PERU S.A' WHERE id>0 AND PROVEEDOR IN ('ENTEL PERÚ SA');
UPDATE regs SET PROVEEDOR = 'ERNAN HUGO RAMON' WHERE id>0 AND PROVEEDOR IN ('ERNAN HUGO RAMON LLULLUY', 'RAMON LLULLEY ERNAN HUGO', 'RAMON LLULLOY ERNAN HUGO');
UPDATE regs SET PROVEEDOR = 'ESCOBAR INGA SUSANA SIBIA' WHERE id>0 AND PROVEEDOR IN ('SUSANA ESCOBAR INGA');
UPDATE regs SET PROVEEDOR = 'ESPALANA PACO ROLANDO' WHERE id>0 AND PROVEEDOR IN ('ESPLANA PACO ROLANDO');
UPDATE regs SET PROVEEDOR = 'ESPINOZA MARTINES MARIA ELENA' WHERE id>0 AND PROVEEDOR IN ('ESPINOZA MARTINEZ MARIA ELENA', 'ESPINZOA MARTINEZ MARIA ELENA', 'ESPINOZAMARTINEZ MARIA ELENA');

UPDATE regs SET PROVEEDOR = 'FELISA LAPA CLEMENTE' WHERE id>0 AND PROVEEDOR IN ('LAPA CLEMENTE FELISA');
UPDATE regs SET PROVEEDOR = 'FERNANDEZ CASO JAIME LUIS' WHERE id>0 AND PROVEEDOR IN ('FERNANDEZ JAIME LUIS');

UPDATE regs SET PROVEEDOR = 'FERRUZO TORRES RICARDO' WHERE id>0 AND PROVEEDOR IN ('RICARDO FERRUZO TORRES', 'FERRUZO TORRES RICARDO SOCRATES');

UPDATE regs SET PROVEEDOR = 'FIVCO MAQUINARIAS & HERRAMIENTAS S.A.C' WHERE id>0 AND PROVEEDOR IN ('FIVCO MAQUINARIAS Y HERRAMIENTAS S.A.C', 'FIVCO MAQUINAS & HERRAMIENTAS S.A.C');
UPDATE regs SET PROVEEDOR = 'FLOR LIFONZO MUNIVE' WHERE id>0 AND PROVEEDOR IN ('LIFONZO MUNIVE FLOR');
UPDATE regs SET PROVEEDOR = 'FLORES CASTILLO ROXANA CATALINA' WHERE id>0 AND PROVEEDOR IN ('FLORES CASTILLO ROZANA CATALINA');
UPDATE regs SET PROVEEDOR = 'MARTIN FLORES JAVIER' WHERE id>0 AND PROVEEDOR IN ('MARTIN FLORES JAVIER','FLORES JAVIER MARTIN');
UPDATE regs SET PROVEEDOR = 'FLORES NESTARES BETSABETH' WHERE id>0 AND PROVEEDOR IN ('FLORES NESTARES BETZA');
UPDATE regs SET PROVEEDOR = 'FLORES PALACIOS CARLOS PIERO' WHERE id>0 AND PROVEEDOR IN ('PALACIOS FALCONI PEDRO CARLOS');
UPDATE regs SET PROVEEDOR = 'FLORES TITO YESABELLA NATALY' WHERE id>0 AND PROVEEDOR IN ('YESABELA NATALY FLORES TITO');
UPDATE regs SET PROVEEDOR = 'JOSE CARLOS FLORES VALLEJO' WHERE id>0 AND PROVEEDOR IN ('FLOREZ VALLEJO JOSE CARLOS' ,'JOSE CARLOS FLORES VALLEJO', 'JOSE CARLOS FLORES VALELJO');

UPDATE regs SET PROVEEDOR = 'TORRES LARA FRACLIN JHOEL' WHERE id>0 AND PROVEEDOR IN ('FRACLIN JHOEL TORRES LAJARA','FRANCLIN JHOEL TORRES LAJARA', 'TORRES LAJARA FRANCLIN JHOEL', 'FRANCLIN HOEL TORRES LAJARA', 'TORRES LARA FRANCIS JHOEL', 'JOEL TORRES LAJARA');

UPDATE regs SET PROVEEDOR = 'FREDOL S.A.C' WHERE id>0 AND PROVEEDOR IN ('FREDO S.A.C');
UPDATE regs SET PROVEEDOR = 'FREDY RAFAEL YOME' WHERE id>0 AND PROVEEDOR IN ('RAFAEL YANCE FREDY');
UPDATE regs SET PROVEEDOR = 'GALINDO VELAZCO FREDY' WHERE id>0 AND PROVEEDOR IN ('GALINDO VELAZO GLENN FREDY');
UPDATE regs SET PROVEEDOR = 'GARAY CAMARGO DOMINGO AUGUSTO' WHERE id>0 AND PROVEEDOR IN ('GARAY CAMARGO DOMINGO AUGUTO');
UPDATE regs SET PROVEEDOR = 'GARCIA INGA MADELEYNE' WHERE id>0 AND PROVEEDOR IN ('GARCIA INGA MADELEYNE EDGY');
UPDATE regs SET PROVEEDOR = 'GARY VERGARA' WHERE id>0 AND PROVEEDOR IN ('VERGARA BREÑA GARY');
UPDATE regs SET PROVEEDOR = 'GAVIDIA LEON ROBERTO ELIAS' WHERE id>0 AND PROVEEDOR IN ('ROBERTO GAVIDIA LEON');
UPDATE regs SET PROVEEDOR = 'GAVILAN EDSON FABIAN JESUS' WHERE id>0 AND PROVEEDOR IN ('GAVILAN TITO EDSON FABIAN JESUS', 'GAVILAN TITO EDISON FABIAN JESUS', 'GAVILAN TITO EDSON FABIAN');
UPDATE regs SET PROVEEDOR = 'GAVILAN TITO EDSON' WHERE id>0 AND PROVEEDOR IN ('GAVILAN TITO EDSON FABIAN');
UPDATE regs SET PROVEEDOR = 'GEOLEMCO S.A.C' WHERE id>0 AND PROVEEDOR IN ('GEOLEMCO S.A.C','GELEMCO S.A.C');

UPDATE regs SET PROVEEDOR = 'GEOVICON S.A.C' WHERE id>0 AND PROVEEDOR IN ('GEOVINCON S.A.C', 'GEOVINCO S.A.C');
UPDATE regs SET PROVEEDOR = 'GILBONIO GARAY LEONOR VANESSA' WHERE id>0 AND PROVEEDOR IN ('VANESSA GILBONIO GARAY');
UPDATE regs SET PROVEEDOR = 'GINA HILARIO RAMOS' WHERE id>0 AND PROVEEDOR IN ('HILARIO RAMOS GINA');
UPDATE regs SET PROVEEDOR = 'GLOBAL PRECISION INSTRUMENTS S.A.C' WHERE id>0 AND PROVEEDOR IN ('GLOBAL PRECISION INTRUMENTS S.A.C', 'GLOBAL PRESICION INSTRUCMENTS SAC');
UPDATE regs SET PROVEEDOR = 'GONZALES CANO BRIGHIT' WHERE id>0 AND PROVEEDOR IN ('GONZALES CANO BRIGHIT MEDALY', 'GONZALES CANO BRIGITH MEDALY');
UPDATE regs SET PROVEEDOR = 'GONZALO ROJAS BERNARD PABLO' WHERE id>0 AND PROVEEDOR IN ('GONZALO ROJAS BERNARD PABLO','GONZALO ROJAS BARNARD PABLO');
UPDATE regs SET PROVEEDOR = 'GRUPO BACCHOCC E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('GRUPO BACHOCC E.I.R.L');

UPDATE regs SET PROVEEDOR = 'GRUPO HIDRORIEGO INGENIEROS S.A.C' WHERE id>0 AND PROVEEDOR IN ('GRUPO HIDRORIEGO INGENIEROS S.A.C', 'GRUPO HIDROGIEGO INGENIEROS S.A.C','GRUPO HRIDRORIEGO INGENIEROS S.A.C');
UPDATE regs SET PROVEEDOR = 'GRUPO HINOSTROZA S.A.C' WHERE id>0 AND PROVEEDOR IN ('GRUPO HINOSTROZA S.A.C', 'GRUPO HINOSTROZA');
UPDATE regs SET PROVEEDOR = 'GRUPO HUARCAYA PEREZ S.A.C' WHERE id>0 AND PROVEEDOR IN ('GRUPO HUARCAYA Y PEREZ S.A.C');

UPDATE regs SET PROVEEDOR = 'GUTIERREZ CORILLOCLLA CINTHIA' WHERE id>0 AND PROVEEDOR IN ('GUTIERREZ CORRILLOCLLA CINTHIA');
UPDATE regs SET PROVEEDOR = 'GUTIERREZ MARQUEZ MARCO ANTONIO' WHERE id>0 AND PROVEEDOR IN ('MARCO ANTONIO MARQUEZ GUTIERREZ');
UPDATE regs SET PROVEEDOR = 'GUZMAN GUZMAN JUAN CARLOS' WHERE id>0 AND PROVEEDOR IN ('GUZMAN GUZMA JUAN CARLOS');
UPDATE regs SET PROVEEDOR = 'HEBER MONTES SULLCARAY' WHERE id>0 AND PROVEEDOR IN ('MONTES SULLCARAY HEBER');
UPDATE regs SET PROVEEDOR = 'HIDROTEL S.C.R.L' WHERE id>0 AND PROVEEDOR IN ('HIDROTK S.C.R.L');
UPDATE regs SET PROVEEDOR = 'HILARIO CABELLO IVETTE ZELLE' WHERE id>0 AND PROVEEDOR IN ('IVETT HILARIO CABELLO');
UPDATE regs SET PROVEEDOR = 'HOMECENTER PERUANOS SA' WHERE id>0 AND PROVEEDOR IN ('HOMECENTERS PERUANOS S.A.C');
UPDATE regs SET PROVEEDOR = 'HORTENCIA VELASCO GUTIERREZ' WHERE id>0 AND PROVEEDOR IN ('VELASCO GUTIERREZ HORTENCIA');
UPDATE regs SET PROVEEDOR = 'HUAMAN ISIDRO ET JHERSON' WHERE id>0 AND PROVEEDOR IN ('JHERSON HUAMAN ISIDRO');
UPDATE regs SET PROVEEDOR = 'HUAMAN SOTO MANUEL ANGEL' WHERE id>0 AND PROVEEDOR IN ('MANUEL HUAMAN SOTO');
UPDATE regs SET PROVEEDOR = 'HUAMANYALLI RAMOS HENRY CLAUDIO' WHERE id>0 AND PROVEEDOR IN ( 'HUAMAN YALLI RAMOS HENRY CLAUDIO','HUAMANYALLI RAMOS HENRY CLAUDIO');
UPDATE regs SET PROVEEDOR = 'HUAMANCAJA MERCADO RABELE' WHERE id>0 AND PROVEEDOR IN ('HUAMANCAJA MAERCADO RABELE','HUAMANCAJA MERCADO RABELE', 'RABELE HUAMANCAJA MERCADO', 'RABELE HUANCAJA MERCAD');

UPDATE regs SET PROVEEDOR = 'HUARCAYA MESCUA VILMA MARUJA' WHERE id>0 AND PROVEEDOR IN ('VILMA HUARCAYA MESCUA');
UPDATE regs SET PROVEEDOR = 'HUAROC PEREZ YESENIA GLORIA' WHERE id>0 AND PROVEEDOR IN ('HUAROC PEREZ YESSENIA GLORIA');
UPDATE regs SET PROVEEDOR = 'HUAYTA MAYTA IVAN LUIS' WHERE id>0 AND PROVEEDOR IN ('IVAN HUAYTA MAYTA');
UPDATE regs SET PROVEEDOR = 'HUAYTAPALLA BAÑOS ELICEO' WHERE id>0 AND PROVEEDOR IN ('HUAYTAPALLA BAÑOS ELICEO','HUAYTALLA BAÑOS ELICEO ADOLFO');
UPDATE regs SET PROVEEDOR = 'HUGO MUNGUIA ABREGU' WHERE id>0 AND PROVEEDOR IN ('MUNGUIA ABREGU HUGO ANTONIO');
UPDATE regs SET PROVEEDOR = 'HYDRAMIN PERU S.A.C' WHERE id>0 AND PROVEEDOR IN ('HYFRAMIN PERU S.A.C');
UPDATE regs SET PROVEEDOR = 'ICHAPAS QUISPE FELIPE' WHERE id>0 AND PROVEEDOR IN ('ICHPAS QUISPE FELIPE');
UPDATE regs SET PROVEEDOR = 'IGNACIO CONSULTORES & CONSTRUCTORES S.A.C' WHERE id>0 AND PROVEEDOR IN ('IGNACIO CONSULTORES & CONSULTORES S.A.C');
UPDATE regs SET PROVEEDOR = 'IMPORACIONES PEREZ S.A.C' WHERE id>0 AND PROVEEDOR IN ('IMPORTACIONES PEREZ S.A.C');

UPDATE regs SET PROVEEDOR = 'IMPORTACIONES ESTEBAN CENTER E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('IMPORTACIONES ETEBAN CENTER E.I.R.L');
UPDATE regs SET PROVEEDOR = 'INDUSTRIA DE ENERGIA INCA E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('INDUSTRIA ENERGIA INCA');
UPDATE regs SET PROVEEDOR = 'INSPIRA GROUP PUBLICIDAD IMAGEN & MARKETING E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('INSPIERA GROUP PUBLICIDAD E.I.R.L','INSPIRA GROUP PUBLICIDAD & IMAGEN E.I.R.L');
UPDATE regs SET PROVEEDOR = 'INSPIRA GROUP PUBLICIDAD IMAGEN & MARKETING E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('INSPIRA GROUP PUBLICIDAD IMAGEN Y MARKETIN', 'INSPIRA GROUP PUBLICIDAD & IMAGEN E.I.R.L');
UPDATE regs SET PROVEEDOR = 'INVERSIONES RODRIZ E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('INVERSIONES RODRIZ E.I.R.L','INVERCIONES RODRIZ E.I.R.L');
UPDATE regs SET PROVEEDOR = 'INVERSINES PALANTE E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('INVERSIONES PALANTE E.I.R.L');

UPDATE regs SET PROVEEDOR = 'INVERSIONES LA INDUSTRIAL S.R.L' WHERE id>0 AND PROVEEDOR IN ('INVERSIONES LA INDUSTRIAL S.R.L','INVERSIONES AL INDUSTRIAL SRL');

UPDATE regs SET PROVEEDOR = 'INVERSIONES ARI DEL PERU S.A.C' WHERE id>0 AND PROVEEDOR IN ('INVERSIONES ARI DEL PERU S.A.C','INVERSIONES ARI DEL CENTRO PERU SAC');

UPDATE regs SET PROVEEDOR = 'INVERSIONES GENERALES CENTAURO INGENIEROS S.A.C' WHERE id>0 AND PROVEEDOR IN ('INVERSIONES GENERALES CENTAURP INGENIEROS S.A.C');

UPDATE regs SET PROVEEDOR = 'INVERSIONES SAN JORGE S.C.R.L' WHERE id>0 AND PROVEEDOR IN ('INVERSIONES SAN JORGE SCRL','INVERSIONES SAN JORGE');

UPDATE regs SET PROVEEDOR = 'INVERSIONES SEÑOR DE ACORIA S.A.C' WHERE id>0 AND PROVEEDOR IN ('INVERSIONES SEÑOR DE ACORIA S.A.C','INVERSIONES SEÑOR DE ACORIA');

UPDATE regs SET PROVEEDOR = 'INVERSIONES YOMARIO S.A.C' WHERE id>0 AND PROVEEDOR IN ('INVERSIONES YOMARO S.A.C');
UPDATE regs SET PROVEEDOR = 'IRIARTE GONZALES BRAYAN EDGAR' WHERE id>0 AND PROVEEDOR IN ('IRIARTE GONZALES BRYAN EDGAR');
UPDATE regs SET PROVEEDOR = 'JC INGENIERIA Y CONSTRUCCION S.A.C' WHERE id>0 AND PROVEEDOR IN ('J C INGENIERIA Y CONSTRUCCION S.A.C');
UPDATE regs SET PROVEEDOR = 'JACKELINE POVIS GARCIA' WHERE id>0 AND PROVEEDOR IN ('JACKLINE POVIS GARCIA');
UPDATE regs SET PROVEEDOR = 'JESUS MONTALVO NOEI KAREN' WHERE id>0 AND PROVEEDOR IN ('JESUS MONTALVO NOEMI KAREN');
UPDATE regs SET PROVEEDOR = 'JHONNY ROMERO LINARES' WHERE id>0 AND PROVEEDOR IN ('ROMERO LINAREZ JHONNY STEVENS');
UPDATE regs SET PROVEEDOR = 'HUAMANYALLI RAMOS HENRY CLAUDIO' WHERE id>0 AND PROVEEDOR IN ('HUAMANYALLI RAMOS HENRY CLAUDIO','JIAMANYALLI RAMOS HENRRY CLAUDIO');

UPDATE regs SET PROVEEDOR = 'JILVER MARTINEZ CHAVEZ' WHERE id>0 AND PROVEEDOR IN ('MARTINEZ CHAVEZ ELI JILVER');
UPDATE regs SET PROVEEDOR = 'JOSE ANGEL VILLA BENDEZU' WHERE id>0 AND PROVEEDOR IN ('VILLA BENDEZU JOSE ANGEL', 'JOSE VILLA BENDEZU');
UPDATE regs SET PROVEEDOR = 'JOSUE NAHUIN SOLANO' WHERE id>0 AND PROVEEDOR IN ('LUIS NAHUIN  SOLANO');
UPDATE regs SET PROVEEDOR = 'SANCHEZ LAZO JUAN CARLOS' WHERE id>0 AND PROVEEDOR IN ('SANCHEZ LAZO JUAN CARLOS','JUAN CARLOS LAZO');

UPDATE regs SET PROVEEDOR = 'JULCA CRUZ JHORZHIÑO MASSHIÑO' WHERE id>0 AND PROVEEDOR IN ('JULCA CRUZ JHORZHIÑO MASSHIÑO','JULCA CRUZ JHOZIÑO MASSIÑO','JULCA CRUZ JHORZHIÑO');

UPDATE regs SET PROVEEDOR = 'KENDY ELVIZ ROJAS TORO' WHERE id>0 AND PROVEEDOR IN ('ROJAS TORO ELVIZ KENDY');
UPDATE regs SET PROVEEDOR = 'KUKIN ERICK USQUIANO USCUVILCA' WHERE id>0 AND PROVEEDOR IN ('USQUIANO USCUVILCA KUKIN ERIK');
UPDATE regs SET PROVEEDOR = 'LADRON DE GUERVARA BASALDUA ESTELA NILDA' WHERE id>0 AND PROVEEDOR IN ('LADRON DE GUEVARA BASALDA ESTELA NILDA', 'LADRON DE GUEVARA BASALDYA ESTELA');
UPDATE regs SET PROVEEDOR = 'LAPTOP CENTER S.A.C' WHERE id>0 AND PROVEEDOR IN ('LAPTOP CENTER S.A.C','LAPTOP CENTER');
UPDATE regs SET PROVEEDOR = 'LAURENTE SANTOS JESSICA' WHERE id>0 AND PROVEEDOR IN ('LAURENTE SANTOS JESSICA MILAGROS');
UPDATE regs SET PROVEEDOR = 'LAVADO MISAYAURI ISAAC JOSUE' WHERE id>0 AND PROVEEDOR IN ('LAVADO MISIYAURI ISAAC JOSUE', 'LAVADO MISIYURI ISAAC JOSUE', 'LAVADO MISIYAURI ISAAC');
UPDATE regs SET PROVEEDOR = 'LAVADO MISAYAURI JOEL GEDEON' WHERE id>0 AND PROVEEDOR IN ('LAVADO MISIYAURI JOEL GEDEON');
UPDATE regs SET PROVEEDOR = 'LIBRERÍA BAZAR SANTA MARIA S.A.C' WHERE id>0 AND PROVEEDOR IN ('LIBRERÍA SANTA MARIA S.A.C');
UPDATE regs SET PROVEEDOR = 'LIZ ZAPATA CALDERON' WHERE id>0 AND PROVEEDOR IN ('ZAPATA CALDERON LIZ FLOR');
UPDATE regs SET PROVEEDOR = 'LIZARBE QUISPE NOE' WHERE id>0 AND PROVEEDOR IN ('NOE LIZARBE QUISPE');
UPDATE regs SET PROVEEDOR = 'LLANTAS Y AROS IMPORTACIONES E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('LLANTAS Y AROS IMPORTACIONES E.I.R.L','LLANTAS Y AROS IMPORT E.I.R.L');
UPDATE regs SET PROVEEDOR = 'LOPEZ ARMES TEODULA COYA' WHERE id>0 AND PROVEEDOR IN ('LOPEZ ARMES TODULA COYA');
UPDATE regs SET PROVEEDOR = 'LOPEZ PEREZ DANIELA' WHERE id>0 AND PROVEEDOR IN ('LOPEZ PEREZ DANIELA REBECA');
UPDATE regs SET PROVEEDOR = 'LUIS ANTONIO SANTIVAÑEZ CASTILLO' WHERE id>0 AND PROVEEDOR IN ('SANTIVAÑEZ CASTILLO LUIS ANTONIO');
UPDATE regs SET PROVEEDOR = 'LUIS QUISPE QUISPE' WHERE id>0 AND PROVEEDOR IN ('QUISPE QUISPE AMERICO LUIS');
UPDATE regs SET PROVEEDOR = 'MADERERA E INVERSIONES CRISTIAN E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('MADERERA E INVERSIONES CRISTIAN E.I.R.L','MADERA E INVERSIONES CRISTIAN S.A.C');

UPDATE regs SET PROVEEDOR = 'MADERERA SEBASTIAN E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('MADERERA SEBASTIAN E.I.R.L','MADERA SEBASTIAN E.I.R.L');
UPDATE regs SET PROVEEDOR = 'MAGDA VELASCO SANTOS' WHERE id>0 AND PROVEEDOR IN ('VELASCO SANTOS DORIS');
UPDATE regs SET PROVEEDOR = 'MAITA PEREZ PAULINO ROBERTO' WHERE id>0 AND PROVEEDOR IN ('ROBERTO APAULINO MAITA PEREZ');
UPDATE regs SET PROVEEDOR = 'MANAGE AND PROTECT YOUR COMPANY S.A.C' WHERE id>0 AND PROVEEDOR IN ('MPC (MANAGE AND PROTECT YOUR COMPANY) S.A.C');
UPDATE regs SET PROVEEDOR = 'MANTARO CASAMAC S.A.C' WHERE id>0 AND PROVEEDOR IN ('MANTARO CASAMAC S.A.C', 'MATARO CASA MAC S.A.C', 'MANTARO CASAMAC', 'MANTRO CASAMAC SAC','MANTARO CASA MAC S.A.C');

UPDATE regs SET PROVEEDOR = 'MANUEL ROJAS ECHEVARRIA' WHERE id>0 AND PROVEEDOR IN ('ROAS ECHEVARRIA MANUEL', 'ROJAS ECHEVARRIA MANUEL GEDEON');

UPDATE regs SET PROVEEDOR = 'MAPFRE PERU COMPAÑÍA DE SEGUROS Y REASEGUROS' WHERE id>0 AND PROVEEDOR IN ('MAPFRE PERU COMPAÑIA DE SEGUROS Y REASEGURO','MAPFRE PERU COMPAÑÍA DE SEGUROS Y REASEGUROS', 'MAPFRE PERU CIA DE SEGUROS S.A','MAPFRE PERU COMAÑIA DE SEGUROS', 'MAPFRE PERU COMPAÑÍA DE SEGUROS', 'MAPRE PERU COMPAÑÍA DE SEGUROS');
UPDATE regs SET PROVEEDOR = 'MARCELIANO SANCHEZ BEETHOVEN' WHERE id>0 AND PROVEEDOR IN ('MARCELINO SANCHEZ BEETHOVEN');
UPDATE regs SET PROVEEDOR = 'MARCELINO SANCHEZ MELVER' WHERE id>0 AND PROVEEDOR IN ('MELVER MARCELINO SANCHEZ', 'SANCHEZ MELVER MARCELINO', 'SANCHEZ MELVER MARCELIANO');
UPDATE regs SET PROVEEDOR = 'MARCO,KIMI,SUSANA,YOSI' WHERE id>0 AND PROVEEDOR IN ('MARCO,KIMI,SUSANA,YOSI 2');
UPDATE regs SET PROVEEDOR = 'MATFER COMPANY S.A.C' WHERE id>0 AND PROVEEDOR IN ('MATFER COMPANY S.A.C','MATFEER COMPANY SAC');

UPDATE regs SET PROVEEDOR = 'MEDIANA JAIME RENAN' WHERE id>0 AND PROVEEDOR IN ('MEDINA JAIME RENAN', 'MEDIDA JAIME RENAN');
UPDATE regs SET PROVEEDOR = 'MEGAREX CPR RA EIRL' WHERE id>0 AND PROVEEDOR IN ('MEGAREX CPR RV E.I.R.L');
UPDATE regs SET PROVEEDOR = 'MEJIA ARAYPOMA MERY' WHERE id>0 AND PROVEEDOR IN ('MEJIA ATAYPOMA NERY', 'MEJIA ATAYPUMA MERY');
UPDATE regs SET PROVEEDOR = 'MELVIN EDUARD ROJAS TORO' WHERE id>0 AND PROVEEDOR IN ('ROJAS TORO EDUARD MELVIN');
UPDATE regs SET PROVEEDOR = 'MENDOZA APARCO YURI ANGEL' WHERE id>0 AND PROVEEDOR IN ('YAURI ANGEL MENDOZA APARCO', 'YURI MENDOZA APARCO');
UPDATE regs SET PROVEEDOR = 'MENDOZA PARIONA SONIA BERNANDINA' WHERE id>0 AND PROVEEDOR IN ('MENDOZA PARIONA SONIA BERNARDINA');
UPDATE regs SET PROVEEDOR = 'MESA PANDO JEAN PAUL SMITH' WHERE id>0 AND PROVEEDOR IN ('MEZA PANDO JEAN PAUL SMITH', 'MEZA PANDO JEAN PAUL');
UPDATE regs SET PROVEEDOR = 'MEZA BERROSPI ROY ULISES' WHERE id>0 AND PROVEEDOR IN ('ROY ULISES MEZA BERROSPI');
UPDATE regs SET PROVEEDOR = 'MIGUEL PITUY CAPCHA' WHERE id>0 AND PROVEEDOR IN ('PITUY CAPCHA MIGUEL HONORIO', 'PITUY CAPACHA MIGUEL HONORIO');
UPDATE regs SET PROVEEDOR = 'MILAGROS MONTES SANABRIA' WHERE id>0 AND PROVEEDOR IN ('MONTES SANABRIA MILAGROS');
UPDATE regs SET PROVEEDOR = 'MIOMEMITA CG S.R.L' WHERE id>0 AND PROVEEDOR IN ('MOMEMITA CG S.R.L');
UPDATE regs SET PROVEEDOR = 'MIRIAM RIOS OSORIO' WHERE id>0 AND PROVEEDOR IN ('RIOS OSORIO MIRIAM RAQUEL');
UPDATE regs SET PROVEEDOR = 'MOLISA HOME CENTER S.A.C' WHERE id>0 AND PROVEEDOR IN ('MOLISA HOME CENTER S.A.C','MOLISA HOMCE CENTER S.A.C');

UPDATE regs SET PROVEEDOR = 'MONTALVO FLORES DE JESUS JULIA MARIA' WHERE id>0 AND PROVEEDOR IN ('MONTALVO FLORES DE JESUS JULIA MARIA','MONTALVO FLORES JESUS JULIA MARIA','MONTALVO FLORES DE JESUS');

UPDATE regs SET PROVEEDOR = 'MONTAÑEZ ADAMA BRYAN MARCELINO' WHERE id>0 AND PROVEEDOR IN ('MONTAÑEZ ADAMA BRAYAN MARCELINO', 'MONTAÑEZ ADAMA BRAYAN');
UPDATE regs SET PROVEEDOR = 'MULTISERVICIOS SAN ESTEBAN E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('MULTISERVICIOS SAN ESTEBAN E.I.R.L','MULTISERVICE SAN ESTEBAN E.I.R.L');

UPDATE regs SET PROVEEDOR = 'MULTISERVICIOS JULI E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('MUTISERVCIOS JULI', 'MULTISERVICIOS JULI E.I.R.L');
UPDATE regs SET PROVEEDOR = 'P&R MULTISERVICIOS E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('P&R MULTISERVICIOS E.I.R.L','MULTISERVICIOS P&R');
UPDATE regs SET PROVEEDOR = 'MUNICIPALIDAD DISTRITAL DE YANACANCHA' WHERE id>0 AND PROVEEDOR IN ('YANACANCHA','MUNI YANACANCHA');

UPDATE regs SET PROVEEDOR = 'MUNICIPALIDAD DE CAJAS' WHERE id>0 AND PROVEEDOR IN ('MUNICIPALIDAD DE CAJS');

UPDATE regs SET PROVEEDOR = 'MUNICIPALIDAD DE SAN PEDRO DE CHUNAN' WHERE id>0 AND PROVEEDOR IN ('MUNICIPALIDAD DISTRITAL SAN PEDRO DE CHUNAN');



UPDATE regs set PROVEEDOR='ZURITA SANCHEZ HERNAN OMAR' WHERE id>0 and PROVEEDOR IN ('ZURITA  SANCHEZ HERNAN OMAR','ZURITA SANCHEZ HERNAN OMAR');



UPDATE regs SET PROVEEDOR = 'NACHO MAQUINARIAS Y HERRAMIENTAS E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('NACHO MAQUINAS Y HERRAMIENTAS E.I.R.L');
UPDATE regs SET PROVEEDOR = 'NATALY TUEROS ABREGÚ' WHERE id>0 AND PROVEEDOR IN ('TUEROS ABREGU NATALY');

UPDATE regs SET PROVEEDOR = 'NEGOCIACIONES PERU WOODS E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('NEGOCIAIONES PERU WOODS E.I.R.L');
UPDATE regs SET PROVEEDOR = 'NEGOCIACIONES Y SERVICENTRO MELGAR S.A.C' WHERE id>0 AND PROVEEDOR IN ('NEGOCIOS Y SERVICENTRO MELGAR S.A.C', 'NEGOCIOAS Y SERVICENTRO MELGAR S.A.C');

UPDATE regs SET PROVEEDOR = 'NILTON PAUCAR' WHERE id>0 AND PROVEEDOR IN ('PAUCAR SOTO NILTON');
UPDATE regs SET PROVEEDOR = 'NOEMI ESPIRITU' WHERE id>0 AND PROVEEDOR IN ('NOEMI ESPIRITU C.');
UPDATE regs SET PROVEEDOR = 'ORE ORE MADELEINE EDITH' WHERE id>0 AND PROVEEDOR IN ('ORE ORE MADELINE EDITH');
UPDATE regs SET PROVEEDOR = 'ORELLANA MAURICIO YURI' WHERE id>0 AND PROVEEDOR IN ('YURI ORELLANA MURICIO');

UPDATE regs SET PROVEEDOR = 'PACHECO PUCUHIAYLA FREDY ROLAN' WHERE id>0 AND PROVEEDOR IN ('PACHECO PUCUHUAYLA FREDY ROLAN');


UPDATE regs SET PROVEEDOR = 'RAUL PACO DE LA TORRE' WHERE id>0 AND PROVEEDOR IN ('RAUL PACO DE LA TORRE','PACO DE LA TORRE');
UPDATE regs SET PROVEEDOR = 'PALOMINO PUACAR RENZO' WHERE id>0 AND PROVEEDOR IN ('RENZO PALOMINO PAUCAR');
UPDATE regs SET PROVEEDOR = 'YRRAZABAL BENDEZU PAOLA KAHERINE' WHERE id>0 AND PROVEEDOR IN ('YRRAZABAL BENDEZU PAOLA KAHERINE','PAOLA YRRAZABAL BENDEZU');

UPDATE regs SET PROVEEDOR = 'PAREDES LAURA YESENIA GRACIELA' WHERE id>0 AND PROVEEDOR IN ('YESENIA PAREDES LAURA');
UPDATE regs SET PROVEEDOR = 'PARRAGA MANTARI SUSANA LORENZA' WHERE id>0 AND PROVEEDOR IN ('SUSANA PARRAGA MANTARI');

UPDATE regs SET PROVEEDOR = 'PAUCAR PALIAN JHONY' WHERE id>0 AND PROVEEDOR IN ('PAUCAR PALINA JHONY');
UPDATE regs SET PROVEEDOR = 'PEREZ AYUNQUE FELIPE' WHERE id>0 AND PROVEEDOR IN ('PEREZ AYUQUE FELIPE');
UPDATE regs SET PROVEEDOR = 'PERULUBE S.A.C'WHERE id>0 AND PROVEEDOR IN ('PERULUBE S.A.C','PERLUBE S.A.C' );
UPDATE regs SET PROVEEDOR = 'PEÑA CAMARGO POMPEYO' WHERE id>0 AND PROVEEDOR IN ('POMPEYO PEÑA CAMARGO');
UPDATE regs SET PROVEEDOR = 'PINTADO AGUILAR JOSE DOLORES' WHERE id>0 AND PROVEEDOR IN ('PINTADOR AGUILAR JOSE DOLORES');
UPDATE regs SET PROVEEDOR = 'POMA BARRETO WALTER' WHERE id>0 AND PROVEEDOR IN ('WALTER POMA BARRETO');
UPDATE regs SET PROVEEDOR = 'POMA HUALI MAYUMI YORKA' WHERE id>0 AND PROVEEDOR IN ('POMA HUALI MIYUMI YORKA');
UPDATE regs SET PROVEEDOR = 'PRODUCTOS SORIA PERU E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('PRODUCTOS SORIA PERU E.I.R.L','PRODUCTO SORIA PERU E.I.R.L');

UPDATE regs SET PROVEEDOR = 'PROYECTOS INNOVADORES SMART JOMARI S.C.R.L' WHERE id>0 AND PROVEEDOR IN ('PROYECTOS INNOVADORES SMART JOMARI','PROYECTOS SMART JOMARI S.R.L');

UPDATE regs SET PROVEEDOR = 'QUICHACA JUÑURICO DIEGO' WHERE id>0 AND PROVEEDOR IN ('QUICHCA JUÑURICO DIEGO');
UPDATE regs SET PROVEEDOR = 'QUINTANA AGUILAR ROBERTO ALFREDO' WHERE id>0 AND PROVEEDOR IN ('QUINTANO AGUILAR ROBERTO ALFREDO');
UPDATE regs SET PROVEEDOR = 'QUISPE ATAYPUMA WILDER HUGO' WHERE id>0 AND PROVEEDOR IN ('QUISPE ATAYPUMA WILMER HUGO');
UPDATE regs SET PROVEEDOR = 'QUISPE MAYTA ROCIO FLOR' WHERE id>0 AND PROVEEDOR IN ('ROCIO FLOR QUISPE MAYTA');
UPDATE regs SET PROVEEDOR = 'RAMOS CALDDERON MARIA FELICIA' WHERE id>0 AND PROVEEDOR IN ('RAMOS CALDERON MARIA FELICIA');
UPDATE regs SET PROVEEDOR = 'RAMOS HUAMANI WUILMER' WHERE id>0 AND PROVEEDOR IN ('WUILMER RAMOS HUAMANI');
UPDATE regs SET PROVEEDOR = 'RAMOS SAYAS EDWIN RONALD' WHERE id>0 AND PROVEEDOR IN ('RONAL RAMOS SAYAS');
UPDATE regs SET PROVEEDOR = 'RAMOS VILLALVA EMERSON' WHERE id>0 AND PROVEEDOR IN ('RAMOS VILLAVA EMERSON');
UPDATE regs SET PROVEEDOR = 'RAUL CAMPOS ORELLANA' WHERE id>0 AND PROVEEDOR IN ('RAUL WILLIAM CAMPOS ORELLANA');
UPDATE regs SET PROVEEDOR = 'RELIGER ZUASNABAR PALOMINO' WHERE id>0 AND PROVEEDOR IN ('ZUASNABAR PALOMINO RELIGER');
UPDATE regs SET PROVEEDOR = 'RENATO MANUEL SAMANIEGO LAZO' WHERE id>0 AND PROVEEDOR IN ('SAMANIEGO LAZO RENATO MANUEL', 'RENATO SAMANIEGO LAZO', 'SAMANIEGO LAZO RENATO');

UPDATE regs SET PROVEEDOR = 'REPRESENTACIONES CANDYS S.R.L' WHERE id>0 AND PROVEEDOR IN ('REPRESENTACIONES CANDYS S.R.L','REPRESENTACIONES CANDYS');
UPDATE regs SET PROVEEDOR = 'REPRESENTACIONES GENERALES ESCOBAR E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('REPRESENTACIONES GENERALES ESCOBAR E.I.R.L', 'REPRESENTACIONES GENERALES ESCOBARL E.I.R.L');

UPDATE regs SET PROVEEDOR = 'REPRESENTACIONES PIERO´S E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('REPRESENTACIONES PEIRO EIRL','REPRESENTACIONES PIEROS E.I.R.L', 'REPRESENTACIONES PIERO´S E.I.R.L', 'REPRESENTACIONES PIEROS');

UPDATE regs SET PROVEEDOR = 'RIVERA INGAROCA EDDY MARGOT' WHERE id>0 AND PROVEEDOR IN ('RIVERA INGAROCA EDDY MARGOTH');
UPDATE regs SET PROVEEDOR = 'RODCON INGENIEROS S.A.C' WHERE id>0 AND PROVEEDOR IN ('RODCON INGENIEROS S.A.C','RODCON INGENIEROS');

UPDATE regs SET PROVEEDOR = 'RODRIGUEZ CONTRERAS YACKELINE' WHERE id>0 AND PROVEEDOR IN ('RODRIGUEZ CONTRERAS YAQUELIN', 'YACKELYN TANIA RODRIGUEZ CONTRERAS');
UPDATE regs SET PROVEEDOR = 'ROJAS TORO YOSEL ISAIAS' WHERE id>0 AND PROVEEDOR IN ('YOSEL ISAIAS ROJAS TORO');
UPDATE regs SET PROVEEDOR = 'ROMAN MUÑOZ VICTOR JAIRO' WHERE id>0 AND PROVEEDOR IN ('ROMAN MUÑOZ VICTOR JAIRO','ROMAN MUÑOZ JAVIER VICTOR','VICTOR JAIRO ROMAN MUÑOZ', 'ROMAS MUÑOZ VICTOR JAIRO', 'VICTOR ROMAN MUÑOZ');

UPDATE regs SET PROVEEDOR = 'ROMANI FELIX PERCY' WHERE id>0 AND PROVEEDOR IN ('ROMANI FELIX PERCY DAVID');
UPDATE regs SET PROVEEDOR = 'ROMANI RAMOS CRIS BRUSS' WHERE id>0 AND PROVEEDOR IN ('ROMANI RAMOS CRISS BRUSS');
UPDATE regs SET PROVEEDOR = 'ROMARIO JERSON TORIBIO AYALA' WHERE id>0 AND PROVEEDOR IN ('TORIBIO AYALA JHERSON ROMARIO');
UPDATE regs SET PROVEEDOR = 'ROMERO ROJAS TEOFANES' WHERE id>0 AND PROVEEDOR IN ('TEOFANES ROMERO ROJAS', 'TEOFANES ROMERO FLORES');

UPDATE regs SET PROVEEDOR = 'SEAJECE EJECUTORES CONSTRUCTORES S.A.C' WHERE id>0 AND PROVEEDOR IN ('SEAJECE EJECUTORES CONSTRUCTORES S.A.C','SAJECE EJECUTORES CONSTRUCTORES S.A.C');
UPDATE regs SET PROVEEDOR = 'SALAZAR CRISPIN YUDITH NAYELI' WHERE id>0 AND PROVEEDOR IN ('SALAZAR CRISPIN YUTIH NAYELI');

UPDATE regs SET PROVEEDOR = 'SAN JUAN INVERSIONES COMERCIALES Y SERVICIOS MULTIPLES SRL' WHERE id>0 AND PROVEEDOR IN ('SAN JUAN INVERSIONES COMERCIALES Y SERVICIOS MULTIPLES');

UPDATE regs SET PROVEEDOR = 'SANABRIA CONDOR YELTSIN MICHAEL' WHERE id>0 AND PROVEEDOR IN ('YELTSIN MICHAEL SANABRIA CONDOR', 'YELSIN MICHAEL SANABRIA CONDOR', 'YELTSIN SANABRIA CONDORI');
UPDATE regs SET PROVEEDOR = 'SAUL WILDER RUIZ NINANYA' WHERE id>0 AND PROVEEDOR IN ('SAUL WUILDER RUIZ NINAYA');

UPDATE regs SET PROVEEDOR = 'SAVFER CONTRACTORS E.I.R.L' WHERE id>0 AND PROVEEDOR IN ('SAVFER CONTRACTORS');

UPDATE regs SET PROVEEDOR = 'SERGIO AMBROSIO ARTEZANO' WHERE id>0 AND PROVEEDOR IN ('EDSON GEORGE AMBROSIO ARTEZANO');


UPDATE regs SET PROVEEDOR = 'SERVICIOS GENERALES PJ FENIX S.C.R.L' WHERE id>0 AND PROVEEDOR IN ('SERVICIOS GENERALES PJ FENK S.C.R.L');

UPDATE regs SET PROVEEDOR = 'SISTEMAS Y TOPOGRAFIA S.A.C' WHERE id>0 AND PROVEEDOR IN ('SISTEMAS Y TOPOGRAFIAS SAC');

UPDATE regs SET PROVEEDOR = 'SOCIEDAD MINERA RL' WHERE id>0 AND PROVEEDOR IN ('SOCIEDAD MINERA RL','SOCIEDAD MINERA DE RL');
UPDATE regs SET PROVEEDOR = 'SOCIO CONSTRUCTOR S.A.C' WHERE id>0 AND PROVEEDOR IN ('SOCIO CONSTUCTOR S.A.C');
UPDATE regs SET PROVEEDOR = 'SOPORTES E INVERSIONES MAYRA S.R.L' WHERE id>0 AND PROVEEDOR IN ('SOPORTES E INVERSIONES MAYRA S.R.L','SOPORTE E INVERSIONES  MAYRA');
UPDATE regs SET PROVEEDOR = 'TORRES SANCHEZ WILLINGTON' WHERE id>0 AND PROVEEDOR IN ('WILLINGTON JHONNY TORRES SANCHEZ');
UPDATE regs SET PROVEEDOR = 'TRANSPORTE CALIFORNIA S.A' WHERE id>0 AND PROVEEDOR IN ('TRASPORTE CALIFORNIA SA', 'TRANSPORTES CALIFORNIA');

UPDATE regs SET PROVEEDOR = 'VASQUEZ CCHENCHO ARAIDA' WHERE id>0 AND PROVEEDOR IN ('VASQUEZ CCENCHO ARAIDA','VASQUEZ CCHENCHO ARAIDA','VASQUEZ CENCHO IRAIDA');

UPDATE regs SET PROVEEDOR = 'VASQUEZ ORIHUELA DEYVI KEVIN' WHERE id>0 AND PROVEEDOR IN ('VASQUEZ ORIHUELA DEYVI KEVIN','VASQUEZ ORIHUELA DAYVI');

UPDATE regs SET PROVEEDOR = 'VELASQUEZ RODRIGUEZ EDUARDO PEDRO' WHERE id>0 AND PROVEEDOR IN ('VELASQUEZ RODRIGUEZ EDUARDO PEDRO','VELAQUEZ RODRIGUEZ EDUARDO PEDRO');

UPDATE regs SET PROVEEDOR = 'VENTURO MEZA JEAN PAUL' WHERE id>0 AND PROVEEDOR IN ('VENTURO MEZA JEAN PAUL','VENTURO MESA JEAN PAUL');

UPDATE regs SET PROVEEDOR = 'VISTONY COMPAÑÍA INDUSTRIAL DEL PERU S.A.C' WHERE id>0 AND PROVEEDOR IN ('VISTONY COMPAÑÍA INDUSTRIAL DEL PERU S.A.C','VICTONY COMPAÑÍA INDUSTRIAL DEL PERU S.A.C');

UPDATE regs SET PROVEEDOR = 'VILCAHUAMAN PAUCAR DIEGO DESAID' WHERE id>0 AND PROVEEDOR IN ('VILCAHUAMAN PAUCAR DIEGO DESAID','VILCAHUAMAN PAUCAR DIEGO DEAID');

UPDATE regs SET PROVEEDOR = 'VILLENA OCHOA YORSHYO ARTEMIO' WHERE id>0 AND PROVEEDOR IN ('VILLENA OCHOA YORSHYO ARTEMIO','VILLENA OCHOA YORSHIO ARTEMIO');
UPDATE regs SET PROVEEDOR = 'YOBERT TORO MENDOZA' WHERE id>0 AND PROVEEDOR IN ('YOBERTH TORO MENDOZA');
UPDATE regs SET PROVEEDOR = 'ZETTACOM S.A.C' WHERE id>0 AND PROVEEDOR IN ('ZETTACOM S.A.C','ZATTACOM S.A.C');
