update regs set COMPROBANTES =1	    WHERE ID>0 AND COMPROBANTES='FACTURA';
update regs set COMPROBANTES =2	    WHERE ID>0 AND COMPROBANTES='RETIRO CREDITO';
update regs set COMPROBANTES =3	    WHERE ID>0 AND COMPROBANTES='BOLETAS VENTA';
update regs set COMPROBANTES =4	    WHERE ID>0 AND COMPROBANTES='DJ';
update regs set COMPROBANTES =5	    WHERE ID>0 AND COMPROBANTES='RECIBO';
update regs set COMPROBANTES =6	    WHERE ID>0 AND COMPROBANTES='TRANS. E/CUENTAS';
update regs set COMPROBANTES =7	    WHERE ID>0 AND COMPROBANTES='COMISION BANCO';
update regs set COMPROBANTES =8	    WHERE ID>0 AND COMPROBANTES='PRESTAMO';
update regs set COMPROBANTES =9	    WHERE ID>0 AND COMPROBANTES='LIQUI. DE COMPRA';
update regs set COMPROBANTES =10    WHERE ID>0 AND COMPROBANTES='BOLETAS PLANILLA';
update regs set COMPROBANTES =11    WHERE ID>0 AND COMPROBANTES='ESTADO DE CUENTA';
update regs set COMPROBANTES =12    WHERE ID>0 AND COMPROBANTES='RH';
update regs set COMPROBANTES =13    WHERE ID>0 AND COMPROBANTES='SENCICO';
update regs set COMPROBANTES =14    WHERE ID>0 AND COMPROBANTES='CONAFOVICER';
update regs set COMPROBANTES =15    WHERE ID>0 AND COMPROBANTES='SUNAT';
update regs set COMPROBANTES =16    WHERE ID>0 AND COMPROBANTES='DEVOLUCIONES';
update regs set COMPROBANTES =17    WHERE ID>0 AND COMPROBANTES='FACTURA CREDITO';

