UPDATE regs set TIPO_DE_CUENTA=1	WHERE ID>0 and TIPO_DE_CUENTA='BCP RODCON';
UPDATE regs set TIPO_DE_CUENTA=2	WHERE ID>0 and TIPO_DE_CUENTA='BCP RODCON DOLARES';
UPDATE regs set TIPO_DE_CUENTA=3	WHERE ID>0 and TIPO_DE_CUENTA='NACION LABOON';
UPDATE regs set TIPO_DE_CUENTA=4	WHERE ID>0 and TIPO_DE_CUENTA='SCOTIABANK RODCON';
UPDATE regs set TIPO_DE_CUENTA=5	WHERE ID>0 and TIPO_DE_CUENTA='NACION CIEL';
UPDATE regs set TIPO_DE_CUENTA=6	WHERE ID>0 and TIPO_DE_CUENTA='PICHINCHA CIEL';
UPDATE regs set TIPO_DE_CUENTA=7	WHERE ID>0 and TIPO_DE_CUENTA='BCP CIEL';
UPDATE regs set TIPO_DE_CUENTA=8	WHERE ID>0 and TIPO_DE_CUENTA='BCP ANDY';
UPDATE regs set TIPO_DE_CUENTA=9	WHERE ID>0 and TIPO_DE_CUENTA='INTERBANK NATY';
UPDATE regs set TIPO_DE_CUENTA=10	WHERE ID>0 and TIPO_DE_CUENTA='BCP NATY';
UPDATE regs set TIPO_DE_CUENTA=11	WHERE ID>0 and TIPO_DE_CUENTA='BANBIF SOLES CIEL';
UPDATE regs set TIPO_DE_CUENTA=12	WHERE ID>0 and TIPO_DE_CUENTA='BANBIF DOLARES CIEL';
UPDATE regs set TIPO_DE_CUENTA=13	WHERE ID>0 and TIPO_DE_CUENTA='BCP CIEL LOGISTICA';
UPDATE regs set TIPO_DE_CUENTA=14	WHERE ID>0 and TIPO_DE_CUENTA='SCOTIABANK CIEL';
UPDATE regs set TIPO_DE_CUENTA=15	WHERE ID>0 and TIPO_DE_CUENTA='BBVA CIEL';
UPDATE regs set TIPO_DE_CUENTA=16	WHERE ID>0 and TIPO_DE_CUENTA='BBVA RODCON';
UPDATE regs set TIPO_DE_CUENTA=17	WHERE ID>0 and TIPO_DE_CUENTA='BCP CIEL DOLARES';
UPDATE regs set TIPO_DE_CUENTA=18	WHERE ID>0 and TIPO_DE_CUENTA='CAJA CHICA';
UPDATE regs set TIPO_DE_CUENTA=19	WHERE ID>0 and TIPO_DE_CUENTA='NACION RODCON';
UPDATE regs set TIPO_DE_CUENTA=20	WHERE ID>0 and TIPO_DE_CUENTA='BANBIF SANNY';
UPDATE regs set TIPO_DE_CUENTA=21	WHERE ID>0 and TIPO_DE_CUENTA='BBVA SANNY';
UPDATE regs set TIPO_DE_CUENTA=22	WHERE ID>0 and TIPO_DE_CUENTA='BBVA ECOHIDRO';
UPDATE regs set TIPO_DE_CUENTA=23	WHERE ID>0 and TIPO_DE_CUENTA='BBVA CASABEN';
UPDATE regs set TIPO_DE_CUENTA=24	WHERE ID>0 and TIPO_DE_CUENTA='BBVA LABOON';
UPDATE regs set TIPO_DE_CUENTA=25	WHERE ID>0 and TIPO_DE_CUENTA='BANBIF LABOON';
UPDATE regs set TIPO_DE_CUENTA=26	WHERE ID>0 and TIPO_DE_CUENTA='BANBIF DOLARES RODCON';
UPDATE regs set TIPO_DE_CUENTA=27	WHERE ID>0 and TIPO_DE_CUENTA='BANBIF SOLES RODCON';
UPDATE regs set TIPO_DE_CUENTA=28	WHERE ID>0 and TIPO_DE_CUENTA='NACION CASABEN';
UPDATE regs set TIPO_DE_CUENTA=29	WHERE ID>0 and TIPO_DE_CUENTA='NACION ECOHIDRO';
UPDATE regs set TIPO_DE_CUENTA=30	WHERE ID>0 and TIPO_DE_CUENTA='BBVA TURPA';
UPDATE regs set TIPO_DE_CUENTA=31	WHERE ID>0 and TIPO_DE_CUENTA='BBVA SALCAHUASI';
UPDATE regs set TIPO_DE_CUENTA=32	WHERE ID>0 and TIPO_DE_CUENTA='BBVA HIDROSOL';
UPDATE regs set TIPO_DE_CUENTA=33	WHERE ID>0 and TIPO_DE_CUENTA='BBVA ANTA';
UPDATE regs set TIPO_DE_CUENTA=34	WHERE ID>0 and TIPO_DE_CUENTA='BBVA RA';
UPDATE regs set TIPO_DE_CUENTA=35	WHERE ID>0 and TIPO_DE_CUENTA='BCP CIEL 2';
UPDATE regs set TIPO_DE_CUENTA=36	WHERE ID>0 and TIPO_DE_CUENTA='CAJA CHICA CIEL';
UPDATE regs set TIPO_DE_CUENTA=37	WHERE ID>0 and TIPO_DE_CUENTA='NACION HIDROSOL';
UPDATE regs set TIPO_DE_CUENTA=38	WHERE ID>0 and TIPO_DE_CUENTA='NACION SALCAHUASI';


/*vERIFICAR LA CUENTA SI EXISTE O NO CON ESE ID U OTRO*/

UPDATE regs set TIPO_DE_CUENTA=39   WHERE ID>0 and TIPO_DE_CUENTA='BBVA CIEL 2DA CTA'