update regs set TRANSACCION=1 WHERE ID>0 AND TRANSACCION='DEPOSITO';
update regs set TRANSACCION=2 WHERE ID>0 AND TRANSACCION='EFECTIVO';
update regs set TRANSACCION=3 WHERE ID>0 AND TRANSACCION='TRANSFERENCIA';
update regs set TRANSACCION=4 WHERE ID>0 AND TRANSACCION='RETIRO';